# Generated by Django 4.0.1 on 2022-11-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_addapitest_apitest_pertest_repapitest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KgTest',
        ),
    ]
