# Generated by Django 4.0.1 on 2022-11-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_delete_kgtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='KgTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeID', models.IntegerField()),
                ('actionName', models.CharField(max_length=120)),
                ('perList', models.CharField(max_length=120, null=True)),
                ('apiList', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
