# Generated by Django 4.1.7 on 2023-03-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0008_delete_addapitest_delete_apitest_delete_kgtest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddApiTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listID', models.IntegerField()),
                ('list', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='ApiTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiID', models.IntegerField()),
                ('apiName', models.CharField(max_length=200)),
                ('inLevel', models.IntegerField()),
                ('outLevel', models.IntegerField()),
                ('addList', models.CharField(blank=True, max_length=200)),
                ('repList', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KgTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeID', models.IntegerField()),
                ('actionName', models.CharField(max_length=120)),
                ('perList', models.CharField(blank=True, max_length=120)),
                ('apiList', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PerTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perID', models.IntegerField()),
                ('perName', models.CharField(max_length=200)),
                ('inLevel', models.IntegerField()),
                ('outLevel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='relTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceID', models.IntegerField()),
                ('sourceAct', models.CharField(max_length=200)),
                ('targetID', models.IntegerField()),
                ('targetAct', models.CharField(max_length=200)),
                ('relation', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='RepApiTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listID', models.IntegerField()),
                ('list', models.CharField(max_length=600)),
            ],
        ),
    ]
