# Generated by Django 4.1.7 on 2023-03-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KgBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeID', models.IntegerField()),
                ('actionName', models.CharField(max_length=120)),
                ('perList', models.CharField(blank=True, max_length=120)),
                ('apiList', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
