# Generated by Django 4.1.7 on 2023-03-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_kgbackup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kgbackup',
            name='nodeID',
            field=models.IntegerField(null=True),
        ),
    ]
