# Generated by Django 4.1.7 on 2023-03-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_kgbackup_nodeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kgbackup',
            name='nodeID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
