# Generated by Django 4.1.7 on 2023-03-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_kgbackup_nodeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kgbackup',
            name='apiList',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='kgbackup',
            name='perList',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
