# Generated by Django 4.1.7 on 2023-03-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_alter_kgbackup_apilist_alter_kgbackup_perlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='relBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceID', models.IntegerField()),
                ('sourceAct', models.CharField(max_length=200)),
                ('targetID', models.IntegerField()),
                ('targetAct', models.CharField(max_length=200)),
                ('relation', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
