# Generated by Django 4.1.7 on 2023-03-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_relbackup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relbackup',
            name='sourceAct',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relbackup',
            name='targetAct',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
