# Generated by Django 4.1.7 on 2023-03-31 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_alter_relbackup_sourceact_alter_relbackup_targetact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kgbackup',
            name='apiList',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='kgbackup',
            name='perList',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='relbackup',
            name='sourceAct',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='relbackup',
            name='targetAct',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
