# Generated by Django 4.1.7 on 2023-04-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_alter_kgbackup_apilist_alter_kgbackup_perlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSDK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listID', models.IntegerField(blank=True)),
                ('list', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='PerSDK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listID', models.IntegerField(blank=True)),
                ('list', models.CharField(max_length=600)),
            ],
        ),
    ]
