# Generated by Django 4.1.7 on 2023-04-03 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_apisdk_persdk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApiSDK',
            new_name='ApiSim',
        ),
    ]
