# Generated by Django 4.1.7 on 2023-04-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_rename_apisdk_apisim'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSDK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listID', models.IntegerField(blank=True)),
                ('list', models.CharField(max_length=600)),
            ],
        ),
    ]
