# Generated by Django 4.1.7 on 2023-04-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_sensitiveapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensitiveApiMini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(blank=True, default='', max_length=200)),
                ('permission', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
