# Generated by Django 4.1.7 on 2023-04-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_sensitiveapimini'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensitiveapimini',
            old_name='permission',
            new_name='name',
        ),
        migrations.AddField(
            model_name='sensitiveapimini',
            name='description',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='sensitiveapimini',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sensitiveapimini',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
