# Generated by Django 4.1.7 on 2023-05-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_rename_permission_sensitiveapimini_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='apiRequsetPer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(blank=True, default='', max_length=250)),
                ('per', models.CharField(blank=True, default='', max_length=250)),
            ],
        ),
    ]
