# Generated by Django 4.1.7 on 2023-05-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_augmentestnode_augmentestrel'),
    ]

    operations = [
        migrations.CreateModel(
            name='augmenTestAPi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiID', models.IntegerField(blank=True)),
                ('apiName', models.CharField(max_length=200)),
                ('inLevel', models.CharField(blank=True, max_length=50)),
                ('outLevel', models.CharField(blank=True, max_length=50)),
                ('addList', models.CharField(blank=True, max_length=200)),
                ('repList', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='augmenTestPer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perID', models.IntegerField()),
                ('perName', models.CharField(max_length=200)),
                ('inLevel', models.IntegerField()),
                ('outLevel', models.IntegerField()),
            ],
        ),
    ]
