# Generated by Django 4.1.7 on 2023-05-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_alter_augmentestper_inlevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='augmentestapi',
            name='apiID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='augmentestper',
            name='perID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
