# Generated by Django 4.1.7 on 2023-07-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_augmentamdapi_augmentamdnode_augmentamdper_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='augmentAPi2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiID', models.IntegerField(blank=True, null=True)),
                ('apiName', models.CharField(max_length=200)),
                ('inLevel', models.CharField(blank=True, max_length=50)),
                ('outLevel', models.CharField(blank=True, max_length=50)),
                ('addList', models.CharField(blank=True, max_length=200)),
                ('repList', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='augmentNode2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeID', models.IntegerField(blank=True, null=True)),
                ('actionName', models.CharField(max_length=120)),
                ('perList', models.CharField(blank=True, default='', max_length=120)),
                ('apiList', models.CharField(blank=True, default='', max_length=120)),
                ('mark', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='augmentPer2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perID', models.IntegerField(blank=True, null=True)),
                ('perName', models.CharField(max_length=200)),
                ('inLevel', models.CharField(blank=True, max_length=50)),
                ('outLevel', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='augmentRel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceID', models.IntegerField()),
                ('sourceAct', models.CharField(blank=True, default='', max_length=200)),
                ('targetID', models.IntegerField()),
                ('targetAct', models.CharField(blank=True, default='', max_length=200)),
                ('relation', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
